### ISSUE TITLE
Continue to check data availability when there are gaps in the dates

### ISSUE THREAD

**Issue by thiagoveloso** [earthlab/smapr#24]
Thanks for this awesome package! It makes it really convenient to download and pre-process SMAP data! However, I have a suggestion to make.

I am trying to download the entire data set of the "SPL2SMP_E" product:

```
# Set dates
seq_dates <- seq(as.Date("2015-03-31"), as.Date("2017-08-31"), by = 1)

# Set products
av_data_l2   <- find_smap(id = "SPL2SMP_E", dates = seq_dates, version = 1)
```
However, I get the following error message:

```
Error in validate_date(id, version, date) : 
  Data are not available for this date. 2015.05.13 does not exist at https://n5eil01u.ecs.nsidc.org/SMAP/SPL2SMP.004/
```

Which means: if at least one day of data is unavailable on the server, the function will not proceed with the data availability check. This forces the user to create several date ranges in order to avoid gaps in the dates, which is not very convenient.

A possible solution would be to ignore the error, to proceed with the check and by the end to inform the user which dates were not available on the server, and allow the download of the remaining data anyway.

Would that be feasible?

Thanks!

**Comment by mbjoseph** [comment]
Thanks for opening this up @thiagoveloso - I agree it's inconvenient to have to specify multiple date ranges to avoid one day for which the data are missing. I suspect the best way to handle this would be to raise a warning instead of an error here:

https://github.com/earthlab/smapr/blob/master/R/find_smap.R#L121

After raising warning(s), then `find_smap()` could proceed. Would a warning better match your expectations for the case when data aren't available?

**Comment by thiagoveloso** [comment]
Hi @mbjoseph , thanks for your fast feedback! I think a warning would work beautifully, particularly if it tells the user how many and which days were unavailable on the server.

Keep up the awesome work!

Cheers,
Thiago.
